/*
 * OpenVidu Embedded API
 * OpenVidu Embedded API
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GenerateToken200Response
 */
class GenerateToken200ResponseTest {
    private final GenerateToken200Response model = new GenerateToken200Response();

    /**
     * Model tests for GenerateToken200Response
     */
    @Test
    void testGenerateToken200Response() {
        // TODO: test GenerateToken200Response
    }

    /**
     * Test the property 'token'
     */
    @Test
    void tokenTest() {
        // TODO: test token
    }

}
