/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.api;

import io.openvidu.embedded.client.ApiException;
import io.openvidu.embedded.model.AddParticipant200Response;
import io.openvidu.embedded.model.EmbeddedTokenOptions;
import io.openvidu.embedded.model.Error;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenViduEmbeddedClient
 */
@Disabled
public class OpenViduEmbeddedClientTest {

    private final OpenViduEmbeddedClient api = new OpenViduEmbeddedClient();

    /**
     * Generate a participant URL for an embedded room
     *
     * Generates a secure URL that allows a participant to join an embedded room.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addParticipantTest() throws ApiException {
        EmbeddedTokenOptions embeddedTokenOptions = null;
        AddParticipant200Response response = api.addParticipant(embeddedTokenOptions);

        // TODO: test validations
    }
}
