/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.openvidu.embedded.model.EmbeddedParticipantPermissions;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * EmbeddedTokenOptions
 */
@JsonPropertyOrder({
  EmbeddedTokenOptions.JSON_PROPERTY_PARTICIPANT_NAME,
  EmbeddedTokenOptions.JSON_PROPERTY_ROOM_NAME,
  EmbeddedTokenOptions.JSON_PROPERTY_PERMISSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class EmbeddedTokenOptions {
  public static final String JSON_PROPERTY_PARTICIPANT_NAME = "participantName";
  @javax.annotation.Nonnull
  private String participantName;

  public static final String JSON_PROPERTY_ROOM_NAME = "roomName";
  @javax.annotation.Nonnull
  private String roomName;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private EmbeddedParticipantPermissions permissions;

  public EmbeddedTokenOptions() {
  }

  public EmbeddedTokenOptions participantName(@javax.annotation.Nonnull String participantName) {
    
    this.participantName = participantName;
    return this;
  }

  /**
   * The name of the participant. This will be used to identify the participant in the room. 
   * @return participantName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTICIPANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getParticipantName() {
    return participantName;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParticipantName(@javax.annotation.Nonnull String participantName) {
    this.participantName = participantName;
  }

  public EmbeddedTokenOptions roomName(@javax.annotation.Nonnull String roomName) {
    
    this.roomName = roomName;
    return this;
  }

  /**
   * The name of the room the participant will join
   * @return roomName
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROOM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoomName() {
    return roomName;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoomName(@javax.annotation.Nonnull String roomName) {
    this.roomName = roomName;
  }

  public EmbeddedTokenOptions permissions(@javax.annotation.Nullable EmbeddedParticipantPermissions permissions) {
    
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmbeddedParticipantPermissions getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable EmbeddedParticipantPermissions permissions) {
    this.permissions = permissions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedTokenOptions embeddedTokenOptions = (EmbeddedTokenOptions) o;
    return Objects.equals(this.participantName, embeddedTokenOptions.participantName) &&
        Objects.equals(this.roomName, embeddedTokenOptions.roomName) &&
        Objects.equals(this.permissions, embeddedTokenOptions.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(participantName, roomName, permissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedTokenOptions {\n");
    sb.append("    participantName: ").append(toIndentedString(participantName)).append("\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `participantName` to the URL query string
    if (getParticipantName() != null) {
      try {
        joiner.add(String.format("%sparticipantName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getParticipantName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `roomName` to the URL query string
    if (getRoomName() != null) {
      try {
        joiner.add(String.format("%sroomName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRoomName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `permissions` to the URL query string
    if (getPermissions() != null) {
      joiner.add(getPermissions().toUrlQueryString(prefix + "permissions" + suffix));
    }

    return joiner.toString();
  }

}

