/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * EmbeddedParticipantPermissions
 */
@JsonPropertyOrder({
  EmbeddedParticipantPermissions.JSON_PROPERTY_CAN_RECORD,
  EmbeddedParticipantPermissions.JSON_PROPERTY_CAN_CHAT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class EmbeddedParticipantPermissions {
  public static final String JSON_PROPERTY_CAN_RECORD = "canRecord";
  @javax.annotation.Nullable
  private Boolean canRecord = true;

  public static final String JSON_PROPERTY_CAN_CHAT = "canChat";
  @javax.annotation.Nullable
  private Boolean canChat = true;

  public EmbeddedParticipantPermissions() {
  }

  public EmbeddedParticipantPermissions canRecord(@javax.annotation.Nullable Boolean canRecord) {
    
    this.canRecord = canRecord;
    return this;
  }

  /**
   * If true, the participant is allowed to record the room. 
   * @return canRecord
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanRecord() {
    return canRecord;
  }


  @JsonProperty(JSON_PROPERTY_CAN_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanRecord(@javax.annotation.Nullable Boolean canRecord) {
    this.canRecord = canRecord;
  }

  public EmbeddedParticipantPermissions canChat(@javax.annotation.Nullable Boolean canChat) {
    
    this.canChat = canChat;
    return this;
  }

  /**
   * If true, the participant can send and receive chat messages during the room. 
   * @return canChat
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAN_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanChat() {
    return canChat;
  }


  @JsonProperty(JSON_PROPERTY_CAN_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanChat(@javax.annotation.Nullable Boolean canChat) {
    this.canChat = canChat;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedParticipantPermissions embeddedParticipantPermissions = (EmbeddedParticipantPermissions) o;
    return Objects.equals(this.canRecord, embeddedParticipantPermissions.canRecord) &&
        Objects.equals(this.canChat, embeddedParticipantPermissions.canChat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRecord, canChat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedParticipantPermissions {\n");
    sb.append("    canRecord: ").append(toIndentedString(canRecord)).append("\n");
    sb.append("    canChat: ").append(toIndentedString(canChat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `canRecord` to the URL query string
    if (getCanRecord() != null) {
      try {
        joiner.add(String.format("%scanRecord%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCanRecord()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `canChat` to the URL query string
    if (getCanChat() != null) {
      try {
        joiner.add(String.format("%scanChat%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCanChat()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

