/* tslint:disable */
/* eslint-disable */
/**
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddParticipant200Response
 */
export interface AddParticipant200Response {
    /**
     * 
     * @type {string}
     * @memberof AddParticipant200Response
     */
    embeddedURL?: string;
}

/**
 * Check if a given object implements the AddParticipant200Response interface.
 */
export function instanceOfAddParticipant200Response(value: object): value is AddParticipant200Response {
    return true;
}

export function AddParticipant200ResponseFromJSON(json: any): AddParticipant200Response {
    return AddParticipant200ResponseFromJSONTyped(json, false);
}

export function AddParticipant200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddParticipant200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'embeddedURL': json['embeddedURL'] == null ? undefined : json['embeddedURL'],
    };
}

export function AddParticipant200ResponseToJSON(json: any): AddParticipant200Response {
    return AddParticipant200ResponseToJSONTyped(json, false);
}

export function AddParticipant200ResponseToJSONTyped(value?: AddParticipant200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'embeddedURL': value['embeddedURL'],
    };
}

