/* tslint:disable */
/* eslint-disable */
/**
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmbeddedParticipantPermissions } from './EmbeddedParticipantPermissions';
import {
    EmbeddedParticipantPermissionsFromJSON,
    EmbeddedParticipantPermissionsFromJSONTyped,
    EmbeddedParticipantPermissionsToJSON,
    EmbeddedParticipantPermissionsToJSONTyped,
} from './EmbeddedParticipantPermissions';

/**
 * 
 * @export
 * @interface EmbeddedTokenOptions
 */
export interface EmbeddedTokenOptions {
    /**
     * The name of the participant. This will be used to identify the participant in the room.
     * 
     * @type {string}
     * @memberof EmbeddedTokenOptions
     */
    participantName: string;
    /**
     * The name of the room the participant will join
     * @type {string}
     * @memberof EmbeddedTokenOptions
     */
    roomName: string;
    /**
     * 
     * @type {EmbeddedParticipantPermissions}
     * @memberof EmbeddedTokenOptions
     */
    permissions?: EmbeddedParticipantPermissions;
}

/**
 * Check if a given object implements the EmbeddedTokenOptions interface.
 */
export function instanceOfEmbeddedTokenOptions(value: object): value is EmbeddedTokenOptions {
    if (!('participantName' in value) || value['participantName'] === undefined) return false;
    if (!('roomName' in value) || value['roomName'] === undefined) return false;
    return true;
}

export function EmbeddedTokenOptionsFromJSON(json: any): EmbeddedTokenOptions {
    return EmbeddedTokenOptionsFromJSONTyped(json, false);
}

export function EmbeddedTokenOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddedTokenOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'participantName': json['participantName'],
        'roomName': json['roomName'],
        'permissions': json['permissions'] == null ? undefined : EmbeddedParticipantPermissionsFromJSON(json['permissions']),
    };
}

export function EmbeddedTokenOptionsToJSON(json: any): EmbeddedTokenOptions {
    return EmbeddedTokenOptionsToJSONTyped(json, false);
}

export function EmbeddedTokenOptionsToJSONTyped(value?: EmbeddedTokenOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'participantName': value['participantName'],
        'roomName': value['roomName'],
        'permissions': EmbeddedParticipantPermissionsToJSON(value['permissions']),
    };
}

