/*
 * OpenVidu Embedded API
 * OpenVidu Embedded API
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.openvidu.embedded.model.EmbeddedParticipantPermissions;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EmbeddedTokenOptions
 */
@JsonPropertyOrder({
  EmbeddedTokenOptions.JSON_PROPERTY_PARTICIPANT_NAME,
  EmbeddedTokenOptions.JSON_PROPERTY_ROOM_NAME,
  EmbeddedTokenOptions.JSON_PROPERTY_PERMISSIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-06T16:34:25.888068618+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class EmbeddedTokenOptions {
  public static final String JSON_PROPERTY_PARTICIPANT_NAME = "participantName";
  @jakarta.annotation.Nonnull
  private String participantName;

  public static final String JSON_PROPERTY_ROOM_NAME = "roomName";
  @jakarta.annotation.Nonnull
  private String roomName;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @jakarta.annotation.Nullable
  private EmbeddedParticipantPermissions permissions;

  public EmbeddedTokenOptions() {
  }

  public EmbeddedTokenOptions participantName(@jakarta.annotation.Nonnull String participantName) {
    
    this.participantName = participantName;
    return this;
  }

  /**
   * The name of the participant.
   * @return participantName
   */
  @jakarta.annotation.Nonnull
  @Schema(example = "OpenVidu", requiredMode = Schema.RequiredMode.REQUIRED, description = "The name of the participant.")
  @JsonProperty(JSON_PROPERTY_PARTICIPANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getParticipantName() {
    return participantName;
  }


  @JsonProperty(JSON_PROPERTY_PARTICIPANT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParticipantName(@jakarta.annotation.Nonnull String participantName) {
    this.participantName = participantName;
  }

  public EmbeddedTokenOptions roomName(@jakarta.annotation.Nonnull String roomName) {
    
    this.roomName = roomName;
    return this;
  }

  /**
   * The name of the room the participant will join.
   * @return roomName
   */
  @jakarta.annotation.Nonnull
  @Schema(example = "OpenViduEmbedded", requiredMode = Schema.RequiredMode.REQUIRED, description = "The name of the room the participant will join.")
  @JsonProperty(JSON_PROPERTY_ROOM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRoomName() {
    return roomName;
  }


  @JsonProperty(JSON_PROPERTY_ROOM_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRoomName(@jakarta.annotation.Nonnull String roomName) {
    this.roomName = roomName;
  }

  public EmbeddedTokenOptions permissions(@jakarta.annotation.Nullable EmbeddedParticipantPermissions permissions) {
    
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @jakarta.annotation.Nullable
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EmbeddedParticipantPermissions getPermissions() {
    return permissions;
  }


  @JsonProperty(JSON_PROPERTY_PERMISSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@jakarta.annotation.Nullable EmbeddedParticipantPermissions permissions) {
    this.permissions = permissions;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedTokenOptions embeddedTokenOptions = (EmbeddedTokenOptions) o;
    return Objects.equals(this.participantName, embeddedTokenOptions.participantName) &&
        Objects.equals(this.roomName, embeddedTokenOptions.roomName) &&
        Objects.equals(this.permissions, embeddedTokenOptions.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(participantName, roomName, permissions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedTokenOptions {\n");
    sb.append("    participantName: ").append(toIndentedString(participantName)).append("\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

