/*
 * OpenVidu Embedded API
 * OpenVidu Embedded API
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EmbeddedParticipantPermissions
 */
@JsonPropertyOrder({
  EmbeddedParticipantPermissions.JSON_PROPERTY_CAN_RECORD,
  EmbeddedParticipantPermissions.JSON_PROPERTY_CAN_CHAT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-06T14:33:32.619759274+01:00[Europe/Madrid]", comments = "Generator version: 7.11.0")
public class EmbeddedParticipantPermissions {
  public static final String JSON_PROPERTY_CAN_RECORD = "canRecord";
  @jakarta.annotation.Nullable
  private Boolean canRecord = true;

  public static final String JSON_PROPERTY_CAN_CHAT = "canChat";
  @jakarta.annotation.Nullable
  private Boolean canChat = true;

  public EmbeddedParticipantPermissions() {
  }

  public EmbeddedParticipantPermissions canRecord(@jakarta.annotation.Nullable Boolean canRecord) {
    
    this.canRecord = canRecord;
    return this;
  }

  /**
   * If true, the participant can record the session.
   * @return canRecord
   */
  @jakarta.annotation.Nullable
  @Schema(example = "true", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "If true, the participant can record the session.")
  @JsonProperty(JSON_PROPERTY_CAN_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanRecord() {
    return canRecord;
  }


  @JsonProperty(JSON_PROPERTY_CAN_RECORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanRecord(@jakarta.annotation.Nullable Boolean canRecord) {
    this.canRecord = canRecord;
  }

  public EmbeddedParticipantPermissions canChat(@jakarta.annotation.Nullable Boolean canChat) {
    
    this.canChat = canChat;
    return this;
  }

  /**
   * If true, the participant can chat in the session.
   * @return canChat
   */
  @jakarta.annotation.Nullable
  @Schema(example = "true", requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "If true, the participant can chat in the session.")
  @JsonProperty(JSON_PROPERTY_CAN_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCanChat() {
    return canChat;
  }


  @JsonProperty(JSON_PROPERTY_CAN_CHAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanChat(@jakarta.annotation.Nullable Boolean canChat) {
    this.canChat = canChat;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmbeddedParticipantPermissions embeddedParticipantPermissions = (EmbeddedParticipantPermissions) o;
    return Objects.equals(this.canRecord, embeddedParticipantPermissions.canRecord) &&
        Objects.equals(this.canChat, embeddedParticipantPermissions.canChat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canRecord, canChat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmbeddedParticipantPermissions {\n");
    sb.append("    canRecord: ").append(toIndentedString(canRecord)).append("\n");
    sb.append("    canChat: ").append(toIndentedString(canChat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

