openapi: 3.0.1
info:
    version: v1
    title: OpenVidu Embedded API
    description: 'OpenVidu Embedded API'
    termsOfService: https://openvidu.io/conditions/terms-of-service/
    contact:
        name: OpenVidu
        email: commercial@openvidu.io
        url: https://openvidu.io/support/

servers:
    - url: http://localhost:6080/v1
      description: Development server

tags:
    - name: Auth
      description: Endpoints for authentication and tokens

paths:
    /embedded/api/token:
        post:
            operationId: generateToken
            summary: Generate an authentication token
            description: Returns a JWT token for authentication.
            tags:
                - Auth
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TokenOptions'

            responses:
                '200':
                    description: Token successfully generated
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    token:
                                        type: string
                                        example: 'eyJhbGciOiJIUzI1...'
                '400':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                '415':
                    description: 'Unsupported Media Type'
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                '500':
                    description: Internal server error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"

components:
    schemas:
        TokenOptions:
            type: object
            required:
                - participantName
                - roomName
            properties:
                participantName:
                    type: string
                    example: 'participant123'
                    description: 'The name of the participant.'
                roomName:
                    type: string
                    example: 'myRoom'
                    description: 'The name of the room the participant will join.'
                permissions:
                    type: object
                    description: 'Optional permissions for the participant.'
                    properties:
                        canRecord:
                            type: boolean
                            example: true
                            description: 'If true, the participant can record the session.'
                        canChat:
                            type: boolean
                            example: true
                            description: 'If true, the participant can chat in the session.'
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                    format: int32
                message:
                    type: string
