/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.openvidu.embedded.model.EmbeddedParticipantPermissions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddedTokenOptions
 */
class EmbeddedTokenOptionsTest {
    private final EmbeddedTokenOptions model = new EmbeddedTokenOptions();

    /**
     * Model tests for EmbeddedTokenOptions
     */
    @Test
    void testEmbeddedTokenOptions() {
        // TODO: test EmbeddedTokenOptions
    }

    /**
     * Test the property 'participantName'
     */
    @Test
    void participantNameTest() {
        // TODO: test participantName
    }

    /**
     * Test the property 'roomName'
     */
    @Test
    void roomNameTest() {
        // TODO: test roomName
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    void permissionsTest() {
        // TODO: test permissions
    }

}
