/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddedParticipantPermissions
 */
class EmbeddedParticipantPermissionsTest {
    private final EmbeddedParticipantPermissions model = new EmbeddedParticipantPermissions();

    /**
     * Model tests for EmbeddedParticipantPermissions
     */
    @Test
    void testEmbeddedParticipantPermissions() {
        // TODO: test EmbeddedParticipantPermissions
    }

    /**
     * Test the property 'canRecord'
     */
    @Test
    void canRecordTest() {
        // TODO: test canRecord
    }

    /**
     * Test the property 'canChat'
     */
    @Test
    void canChatTest() {
        // TODO: test canChat
    }

}
