/* tslint:disable */
/* eslint-disable */
/**
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddParticipant200Response,
  EmbeddedTokenOptions,
} from '../models/index';
import {
    AddParticipant200ResponseFromJSON,
    AddParticipant200ResponseToJSON,
    EmbeddedTokenOptionsFromJSON,
    EmbeddedTokenOptionsToJSON,
} from '../models/index';

export interface AddParticipantRequest {
    embeddedTokenOptions: EmbeddedTokenOptions;
}

/**
 * 
 */
export class OpenViduEmbeddedClient extends runtime.BaseAPI {

    /**
     * Generates a secure URL that allows a participant to join an embedded room.
     * Generate a participant URL for an embedded room
     */
    async addParticipantRaw(requestParameters: AddParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddParticipant200Response>> {
        if (requestParameters['embeddedTokenOptions'] == null) {
            throw new runtime.RequiredError(
                'embeddedTokenOptions',
                'Required parameter "embeddedTokenOptions" was null or undefined when calling addParticipant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/participant`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EmbeddedTokenOptionsToJSON(requestParameters['embeddedTokenOptions']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddParticipant200ResponseFromJSON(jsonValue));
    }

    /**
     * Generates a secure URL that allows a participant to join an embedded room.
     * Generate a participant URL for an embedded room
     */
    async addParticipant(embeddedTokenOptions: EmbeddedTokenOptions, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddParticipant200Response> {
        const response = await this.addParticipantRaw({ embeddedTokenOptions: embeddedTokenOptions }, initOverrides);
        return await response.value();
    }

}
