/*
 * OpenVidu Embedded API
 * The OpenVidu Embedded API allows seamless integration of interactive video rooms into external applications via an iframe. This API provides endpoints to manage participants, generate secure access URLs, and configure session settings for an embedded experience. 
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.openvidu.embedded.api;

import com.fasterxml.jackson.core.type.TypeReference;

import io.openvidu.embedded.client.ApiException;
import io.openvidu.embedded.client.ApiClient;
import io.openvidu.embedded.client.BaseApi;
import io.openvidu.embedded.client.Configuration;
import io.openvidu.embedded.client.Pair;

import io.openvidu.embedded.model.AddParticipant200Response;
import io.openvidu.embedded.model.EmbeddedTokenOptions;
import io.openvidu.embedded.model.Error;


import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class OpenViduEmbeddedClient extends BaseApi {

  public OpenViduEmbeddedClient() {
    super(Configuration.getDefaultApiClient());
  }

  public OpenViduEmbeddedClient(ApiClient apiClient) {
    super(apiClient);
  }

  /**
   * Generate a participant URL for an embedded room
   * Generates a secure URL that allows a participant to join an embedded room.
   * @param embeddedTokenOptions  (required)
   * @return AddParticipant200Response
   * @throws ApiException if fails to make API call
   */
  public AddParticipant200Response addParticipant(EmbeddedTokenOptions embeddedTokenOptions) throws ApiException {
    return this.addParticipant(embeddedTokenOptions, Collections.emptyMap());
  }


  /**
   * Generate a participant URL for an embedded room
   * Generates a secure URL that allows a participant to join an embedded room.
   * @param embeddedTokenOptions  (required)
   * @param additionalHeaders additionalHeaders for this call
   * @return AddParticipant200Response
   * @throws ApiException if fails to make API call
   */
  public AddParticipant200Response addParticipant(EmbeddedTokenOptions embeddedTokenOptions, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = embeddedTokenOptions;
    
    // verify the required parameter 'embeddedTokenOptions' is set
    if (embeddedTokenOptions == null) {
      throw new ApiException(400, "Missing the required parameter 'embeddedTokenOptions' when calling addParticipant");
    }
    
    // create path and map variables
    String localVarPath = "/participant";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    
    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    TypeReference<AddParticipant200Response> localVarReturnType = new TypeReference<AddParticipant200Response>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  @Override
  public <T> T invokeAPI(String url, String method, Object request, TypeReference<T> returnType, Map<String, String> additionalHeaders) throws ApiException {
    String localVarPath = url.replace(apiClient.getBaseURL(), "");
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarHeaderParams.putAll(additionalHeaders);

    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] {  };

    return apiClient.invokeAPI(
      localVarPath,
        method,
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        request,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        returnType
    );
  }
}
