/*
 * OpenVidu Embedded API
 * OpenVidu Embedded API
 *
 * The version of the OpenAPI document: v1
 * Contact: commercial@openvidu.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openvidu.embedded.api;

import io.openvidu.embedded.model.EmbeddedTokenOptions;
import io.openvidu.embedded.model.Error;
import io.openvidu.embedded.model.GenerateToken200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for EmbeddedAuthApi
 */
@Disabled
public class EmbeddedAuthApiTest {

    private final EmbeddedAuthApi api = new EmbeddedAuthApi();

    
    /**
     * Generate an embedded authentication token
     *
     * 
     */
    @Test
    public void generateTokenTest()  {
        EmbeddedTokenOptions embeddedTokenOptions = null;
        GenerateToken200Response response = api.generateToken(embeddedTokenOptions);

        // TODO: test validations
    }
    
}