name: CI

on:
  push:
    paths:
      - 'openvidu-call-front/**'

jobs:
  unit_test:
    name: OpenVidu Call CI
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Remove package-lock
      run: rm openvidu-call-front/package-lock.json
    - name: Install dependencies
      run: npm install --prefix openvidu-call-front
    - name: Run OpenVidu Call unit tests
      run: npm run test --prefix openvidu-call-front
    - name: Build openvidu-agular
      run: npm run build:openvidu-angular --prefix openvidu-call-front
    - name: Build OpenVidu Webcomponent
      run: npm run build:openvidu-webcomponent --prefix openvidu-call-front